In [12]:
import h5py
import numpy as np
from itertools import combinations
from itertools import chain

from numpy.f2py.auxfuncs import throw_error

In [2]:
def load_h5_file(file, num_cost_matrices):
    """Loads the train and test embeddings"""
    with h5py.File(file, 'r') as f:
        cost_matrices = {i:np.array(f[f'cost_matrix_{i}']) for i in range(num_cost_matrices)}
    return cost_matrices


In [3]:
len_dataset = 188
num_cost_matrices = len(list(combinations(range(len_dataset), r=2)))

print(f'Number of cost matrices: {num_cost_matrices}')

cost_matrices = load_h5_file('../data/cost_matrices.h5', num_cost_matrices)

Number of cost matrices: 17578


In [4]:
cost_matrices[0]

array([[0.13855484, 0.13845885, 1.84178903, 8.33910386, 4.33924013,
        1.54351854, 1.62207349, 1.62207708, 4.26150579, 8.12694368,
        1.97717433, 0.70526678, 1.67934353, 1.01150449, 4.58241239,
        4.76704108, 4.76704108],
       [1.36842527, 1.36843859, 1.13961124, 7.90360381, 3.57798544,
        0.53724399, 0.73316307, 0.73315077, 3.48328601, 7.67941813,
        1.34748111, 2.10670704, 2.37059793, 0.71430031, 4.63460039,
        5.01832703, 5.01832703],
       [2.45242473, 2.45243216, 2.27469461, 7.58660316, 2.93104686,
        2.04664173, 2.10657052, 2.10656624, 2.81480159, 7.35370117,
        2.38405153, 3.00860427, 3.24260571, 2.11382245, 5.16500119,
        5.23503958, 5.23503958],
       [1.36098197, 1.36099536, 1.1403106 , 7.90370468, 3.57820825,
        0.5387259 , 0.73424967, 0.73423739, 3.48351488, 7.67952195,
        1.34807263, 2.09980534, 2.36722034, 0.71541556, 4.6336976 ,
        5.01794937, 5.01794937],
       [0.27703624, 0.27700247, 1.96837194, 8.436694

In [68]:
"""
Creating sub matrices
Input:
Matrix to bi sliced
Where to split vertical (need to be lists)
Where to split horizontal (need to be lists)

Output:
List of the Sub Matrices for teh given Matrix
"""
def creat_sub_matrices_greedy(matrices, vertical_split, horizontal_split):
    if not isinstance(vertical_split, list) or not isinstance(horizontal_split, list): return "Invalid input" # Check if vertical and Horizontal are lists
    vertical_slices = np.vsplit(matrices, vertical_split) #Vertical split
    sub_matrices = list(chain(*[np.hsplit(x, horizontal_split) for x in vertical_slices])) # horizontal Split
    return sub_matrices

In [93]:
sub_matrices = creat_sub_matrices_greedy(cost_matrices[0], [6], [8])
sub_matrices[0]

array([[0.13855484, 0.13845885, 1.84178903, 8.33910386, 4.33924013,
        1.54351854, 1.62207349, 1.62207708],
       [1.36842527, 1.36843859, 1.13961124, 7.90360381, 3.57798544,
        0.53724399, 0.73316307, 0.73315077],
       [2.45242473, 2.45243216, 2.27469461, 7.58660316, 2.93104686,
        2.04664173, 2.10657052, 2.10656624],
       [1.36098197, 1.36099536, 1.1403106 , 7.90370468, 3.57820825,
        0.5387259 , 0.73424967, 0.73423739],
       [0.27703624, 0.27700247, 1.96837194, 8.43669469, 4.50169187,
        1.6925447 , 1.76448533, 1.76448758],
       [1.26254947, 1.26254331, 2.44857401, 8.58986845, 4.77265652,
        2.23287191, 2.28788746, 2.28788888]])

In [85]:
all_cost_matrices_sub = []
for i in range(num_cost_matrices):
    all_cost_matrices_sub.append(creat_sub_matrices_greedy(cost_matrices[i], [round(len(cost_matrices[i]) / 2)], [round(len(cost_matrices[i][0]) / 2)]))

In [86]:
all_cost_matrices_sub[500][0]

array([[0.40295774, 0.7182835 , 1.82759752, 3.11589766, 1.82759752,
        0.7182835 , 1.82794393, 1.50382818, 2.85174422, 4.22395978],
       [0.78539989, 1.00058748, 2.3064789 , 3.57711677, 2.3064789 ,
        1.00058748, 2.30675339, 1.89106334, 3.27924821, 4.13799719],
       [1.68267662, 1.63651132, 2.29179382, 3.6476135 , 2.29179382,
        1.63651132, 2.29207007, 1.96363504, 3.35375945, 4.75870959],
       [2.31029955, 2.2013379 , 2.01176577, 1.15497558, 2.01176577,
        2.2013379 , 2.01208047, 1.92969437, 1.65120875, 5.13118197],
       [1.47057997, 1.31491228, 0.14135507, 2.20070546, 0.14135507,
        1.31491228, 0.1457654 , 0.67332711, 2.18897688, 5.08209587],
       [0.33230907, 0.27701425, 1.60529295, 3.09516978, 1.60529295,
        0.27701425, 1.60568732, 1.14076697, 2.80035454, 4.44024471]])

In [88]:
all_cost_matrices_sub[1000][0]

array([[1.41663042e+00, 1.41663042e+00, 4.97740474e+00, 1.71907095e+00,
        1.30047794e+00, 1.71907096e+00, 4.97740478e+00, 1.78666707e+01,
        1.78666708e+01, 4.97740521e+00, 1.71907095e+00, 1.30047794e+00,
        1.71907095e+00, 4.97740502e+00],
       [1.41659105e+00, 1.41659105e+00, 4.97741619e+00, 1.71903850e+00,
        1.30054248e+00, 1.71903851e+00, 4.97741623e+00, 1.78666856e+01,
        1.78666857e+01, 4.97741666e+00, 1.71903851e+00, 1.30054248e+00,
        1.71903851e+00, 4.97741647e+00],
       [9.67878446e-01, 9.67878446e-01, 3.65277318e+00, 2.47133409e+00,
        2.87613993e+00, 2.47133409e+00, 3.65277321e+00, 1.67244900e+01,
        1.67244901e+01, 3.65277368e+00, 2.47133410e+00, 2.87613993e+00,
        2.47133409e+00, 3.65277346e+00],
       [1.39503667e+01, 1.39503667e+01, 9.99204276e+00, 1.44594867e+01,
        1.45428464e+01, 1.44594867e+01, 9.99204270e+00, 4.47982227e+00,
        4.47982234e+00, 9.99204211e+00, 1.44594867e+01, 1.45428464e+01,
        1.445

In [89]:
all_cost_matrices_sub[1000][1]

array([[ 1.41663042,  1.41663042,  4.53574837,  4.75825614,  4.75825614,
         4.53574836,  4.75825614,  4.75825614,  4.53574836,  4.75825614,
         4.75825614,  4.53574837,  4.75825613,  4.75825613],
       [ 1.41659105,  1.41659105,  4.53545617,  4.75798866,  4.75798866,
         4.53545616,  4.75798866,  4.75798866,  4.53545616,  4.75798866,
         4.75798866,  4.53545617,  4.75798865,  4.75798865],
       [ 0.96787845,  0.96787845,  4.57830632,  4.86496271,  4.86496271,
         4.57830632,  4.86496271,  4.86496271,  4.57830632,  4.86496271,
         4.86496271,  4.57830631,  4.86496271,  4.86496271],
       [13.95036671, 13.95036671, 14.39727805, 13.93980805, 13.93980805,
        14.39727813, 13.93980801, 13.93980801, 14.39727813, 13.93980801,
        13.93980801, 14.39727805, 13.93980807, 13.93980807],
       [17.49802161, 17.49802161, 17.74810509, 17.2813133 , 17.2813133 ,
        17.74810517, 17.28131327, 17.28131327, 17.74810517, 17.28131327,
        17.28131327, 17.74

In [90]:
all_cost_matrices_sub[1000][2]

array([[16.95534871, 16.95534871, 13.11376467, 17.33025175, 17.39435385,
        17.33025175, 13.11376462,  2.98162991,  2.98163005, 13.113764  ,
        17.33025175, 17.39435385, 17.33025175, 13.11376428],
       [ 2.55653538,  2.55653538,  4.8555335 ,  1.29345805,  2.66156277,
         1.29345804,  4.85553352, 17.18935174, 17.18935187,  4.85553384,
         1.29345805,  2.66156277,  1.29345804,  4.85553371],
       [ 2.44977128,  2.44977128,  5.50195983,  0.84876771,  1.95261026,
         0.84876772,  5.50195987, 18.06315461, 18.06315474,  5.50196026,
         0.84876771,  1.95261027,  0.84876772,  5.50196008],
       [ 0.79800749,  0.79800749,  4.7230165 ,  1.80649117,  1.98702699,
         1.80649118,  4.72301653, 17.76072644, 17.76072657,  4.72301699,
         1.80649118,  1.98702699,  1.80649117,  4.72301679],
       [ 4.6380783 ,  4.6380783 ,  6.27178017,  4.93669821,  4.88141967,
         4.93669821,  6.27178021, 17.7004127 , 17.70041285,  6.27178047,
         4.93669823,  4.88

In [91]:
all_cost_matrices_sub[1000][3]

array([[1.69553487e+01, 1.69553487e+01, 1.72041109e+01, 1.67538760e+01,
        1.67538760e+01, 1.72041110e+01, 1.67538760e+01, 1.67538760e+01,
        1.72041110e+01, 1.67538760e+01, 1.67538760e+01, 1.72041109e+01,
        1.67538760e+01, 1.67538760e+01],
       [2.55653538e+00, 2.55653538e+00, 4.96044258e+00, 5.19589775e+00,
        5.19589775e+00, 4.96044259e+00, 5.19589775e+00, 5.19589775e+00,
        4.96044259e+00, 5.19589775e+00, 5.19589775e+00, 4.96044259e+00,
        5.19589774e+00, 5.19589774e+00],
       [2.44977128e+00, 2.44977128e+00, 4.89532144e+00, 5.00957133e+00,
        5.00957133e+00, 4.89532145e+00, 5.00957133e+00, 5.00957133e+00,
        4.89532145e+00, 5.00957133e+00, 5.00957133e+00, 4.89532146e+00,
        5.00957132e+00, 5.00957132e+00],
       [7.98007491e-01, 7.98007491e-01, 4.51313540e+00, 4.85412850e+00,
        4.85412850e+00, 4.51313540e+00, 4.85412850e+00, 4.85412850e+00,
        4.51313540e+00, 4.85412850e+00, 4.85412850e+00, 4.51313540e+00,
        4.854