In [1]:
import h5py
import numpy as np
from itertools import combinations
from itertools import chain

In [2]:
def load_h5_file(file, num_cost_matrices):
    """Loads the train and test embeddings"""
    with h5py.File(file, 'r') as f:
        cost_matrices = {i:np.array(f[f'cost_matrix_{i}']) for i in range(num_cost_matrices)}
    return cost_matrices


In [3]:
len_dataset = 188
num_cost_matrices = len(list(combinations(range(len_dataset), r=2)))

print(f'Number of cost matrices: {num_cost_matrices}')

cost_matrices = load_h5_file('../data/cost_matrices.h5', num_cost_matrices)

Number of cost matrices: 17578


In [4]:
cost_matrices[0]

array([[0.13855484, 0.13845885, 1.84178903, 8.33910386, 4.33924013,
        1.54351854, 1.62207349, 1.62207708, 4.26150579, 8.12694368,
        1.97717433, 0.70526678, 1.67934353, 1.01150449, 4.58241239,
        4.76704108, 4.76704108],
       [1.36842527, 1.36843859, 1.13961124, 7.90360381, 3.57798544,
        0.53724399, 0.73316307, 0.73315077, 3.48328601, 7.67941813,
        1.34748111, 2.10670704, 2.37059793, 0.71430031, 4.63460039,
        5.01832703, 5.01832703],
       [2.45242473, 2.45243216, 2.27469461, 7.58660316, 2.93104686,
        2.04664173, 2.10657052, 2.10656624, 2.81480159, 7.35370117,
        2.38405153, 3.00860427, 3.24260571, 2.11382245, 5.16500119,
        5.23503958, 5.23503958],
       [1.36098197, 1.36099536, 1.1403106 , 7.90370468, 3.57820825,
        0.5387259 , 0.73424967, 0.73423739, 3.48351488, 7.67952195,
        1.34807263, 2.09980534, 2.36722034, 0.71541556, 4.6336976 ,
        5.01794937, 5.01794937],
       [0.27703624, 0.27700247, 1.96837194, 8.436694

In [5]:
"""
Creating sub matrices
Input:
Matrix to bi sliced
Where to split vertical (need to be lists)
Where to split horizontal (need to be lists)

Output:
List of the Sub Matrices for teh given Matrix
"""
def creat_sub_matrices_greedy(matrices, vertical_split, horizontal_split):
    if not isinstance(vertical_split, list) or not isinstance(horizontal_split, list): return "Invalid input" # Check if vertical and Horizontal are lists
    vertical_slices = np.vsplit(matrices, vertical_split) #Vertical split
    sub_matrices = list(chain(*[np.hsplit(x, horizontal_split) for x in vertical_slices])) # horizontal Split
    return sub_matrices

In [6]:
sub_matrices = creat_sub_matrices_greedy(cost_matrices[0], [6], [8])
sub_matrices[0]

array([[0.13855484, 0.13845885, 1.84178903, 8.33910386, 4.33924013,
        1.54351854, 1.62207349, 1.62207708],
       [1.36842527, 1.36843859, 1.13961124, 7.90360381, 3.57798544,
        0.53724399, 0.73316307, 0.73315077],
       [2.45242473, 2.45243216, 2.27469461, 7.58660316, 2.93104686,
        2.04664173, 2.10657052, 2.10656624],
       [1.36098197, 1.36099536, 1.1403106 , 7.90370468, 3.57820825,
        0.5387259 , 0.73424967, 0.73423739],
       [0.27703624, 0.27700247, 1.96837194, 8.43669469, 4.50169187,
        1.6925447 , 1.76448533, 1.76448758],
       [1.26254947, 1.26254331, 2.44857401, 8.58986845, 4.77265652,
        2.23287191, 2.28788746, 2.28788888]])

In [7]:
all_cost_matrices_sub = []
for i in range(num_cost_matrices):
    all_cost_matrices_sub.append(creat_sub_matrices_greedy(cost_matrices[i], [round(len(cost_matrices[i]) / 2)], [round(len(cost_matrices[i][0]) / 2)]))

In [8]:
all_cost_matrices_sub[0][0]

array([[0.13855484, 0.13845885, 1.84178903, 8.33910386, 4.33924013,
        1.54351854, 1.62207349, 1.62207708],
       [1.36842527, 1.36843859, 1.13961124, 7.90360381, 3.57798544,
        0.53724399, 0.73316307, 0.73315077],
       [2.45242473, 2.45243216, 2.27469461, 7.58660316, 2.93104686,
        2.04664173, 2.10657052, 2.10656624],
       [1.36098197, 1.36099536, 1.1403106 , 7.90370468, 3.57820825,
        0.5387259 , 0.73424967, 0.73423739],
       [0.27703624, 0.27700247, 1.96837194, 8.43669469, 4.50169187,
        1.6925447 , 1.76448533, 1.76448758],
       [1.26254947, 1.26254331, 2.44857401, 8.58986845, 4.77265652,
        2.23287191, 2.28788746, 2.28788888]])

In [9]:
all_cost_matrices_sub[0][0]

array([[0.13855484, 0.13845885, 1.84178903, 8.33910386, 4.33924013,
        1.54351854, 1.62207349, 1.62207708],
       [1.36842527, 1.36843859, 1.13961124, 7.90360381, 3.57798544,
        0.53724399, 0.73316307, 0.73315077],
       [2.45242473, 2.45243216, 2.27469461, 7.58660316, 2.93104686,
        2.04664173, 2.10657052, 2.10656624],
       [1.36098197, 1.36099536, 1.1403106 , 7.90370468, 3.57820825,
        0.5387259 , 0.73424967, 0.73423739],
       [0.27703624, 0.27700247, 1.96837194, 8.43669469, 4.50169187,
        1.6925447 , 1.76448533, 1.76448758],
       [1.26254947, 1.26254331, 2.44857401, 8.58986845, 4.77265652,
        2.23287191, 2.28788746, 2.28788888]])

In [10]:
all_cost_matrices_sub[0][1]

array([[4.26150579, 8.12694368, 1.97717433, 0.70526678, 1.67934353,
        1.01150449, 4.58241239, 4.76704108, 4.76704108],
       [3.48328601, 7.67941813, 1.34748111, 2.10670704, 2.37059793,
        0.71430031, 4.63460039, 5.01832703, 5.01832703],
       [2.81480159, 7.35370117, 2.38405153, 3.00860427, 3.24260571,
        2.11382245, 5.16500119, 5.23503958, 5.23503958],
       [3.48351488, 7.67952195, 1.34807263, 2.09980534, 2.36722034,
        0.71541556, 4.6336976 , 5.01794937, 5.01794937],
       [4.42680932, 8.22705119, 2.09559409, 0.54436064, 1.60346112,
        1.12758955, 4.61384684, 4.82365019, 4.82365019],
       [4.70209051, 8.38405579, 2.55196771, 1.12847232, 1.29389919,
        1.81451678, 4.50919282, 4.5602035 , 4.5602035 ]])

In [11]:
all_cost_matrices_sub[0][2]

array([[3.8571529 , 3.85728103, 4.27279025, 9.05244965, 5.99395358,
        4.25690318, 4.26181226, 4.26175755],
       [1.68685188, 1.68685811, 2.63469225, 8.70719146, 4.96237753,
        2.4354887 , 2.48605054, 2.48604837],
       [1.74142389, 1.7414084 , 2.77886018, 8.74686992, 5.03135994,
        2.59084472, 2.63838057, 2.63838522],
       [1.0489629 , 1.04892411, 2.60365637, 8.69059557, 4.9355479 ,
        2.40199692, 2.45317496, 2.4531826 ],
       [4.60078965, 4.60090267, 4.63830696, 8.83470472, 6.05458009,
        4.64374796, 4.65495218, 4.65489949],
       [4.80277771, 4.80288164, 4.89554476, 8.37226051, 5.94933366,
        4.98596714, 4.9846615 , 4.98461426],
       [4.80277771, 4.80288164, 4.89554476, 8.37226051, 5.94933366,
        4.98596714, 4.9846615 , 4.98461426]])

In [12]:
all_cost_matrices_sub[0][3]

array([[5.96715666, 8.86589131, 4.31855516, 3.80540993, 3.91078517,
        4.06897398, 2.5126827 , 4.06436983, 4.06436983],
       [4.89454013, 8.50421691, 2.7310446 , 1.66347551, 0.13842783,
        2.00529141, 4.9204718 , 5.04459557, 5.04459557],
       [4.96448022, 8.54484146, 2.87038546, 1.60244598, 0.41038485,
        2.17878516, 4.94067311, 4.96649263, 4.96649263],
       [4.86736664, 8.48722194, 2.70112804, 0.40010909, 1.80267871,
        1.91938257, 4.74711006, 4.75523324, 4.75523324],
       [6.03570288, 8.65349668, 4.65445803, 4.71905684, 4.9471019 ,
        4.59811514, 0.08263569, 3.74822884, 3.74822884],
       [5.95108043, 8.19741178, 4.87904504, 4.80001732, 5.07339182,
        4.93200601, 3.7592952 , 0.04097388, 0.04097388],
       [5.95108043, 8.19741178, 4.87904504, 4.80001732, 5.07339182,
        4.93200601, 3.7592952 , 0.04097388, 0.04097388]])